"""empty message

Revision ID: 29b052ee87b4
Revises: 36b93d81ad60
Create Date: 2015-01-28 11:52:10.897711

"""

# revision identifiers, used by Alembic.
revision = '29b052ee87b4'
down_revision = '36b93d81ad60'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
